### ISSUE TITLE
streaming API 502

### ISSUE THREAD

**Issue by mason1900** [doubanius/doubanius-tertius#9]
直接结果是用户不会收到通知。另外还有有新嘟文时时间线顶部无法自动刷新。挂掉的API至少有：
donotban.com/api/v1/streaming/?stream=user
donotban.com/api/v1/streaming/?stream=public
原因可能是nginx设置不正确。以下为两个相关的github链接：
https://github.com/tootsuite/mastodon/issues/809
https://gist.github.com/witcheslive/dbbed7644ad6a639a3d1d6b59a8c9597

**Comment by doubanius** [comment]
mastodon-streaming的log无异常，可否对API问题进行详细说明？谢谢~

**Comment by mason1900** [comment]
那么请参考第二个链接，如果是nginx配置不正确，那么mastodon-streaming的log应该并不会留下异常。。。
复现bug的方法：使用Chrome或者Firefox打开里瓣任何页面，然后按F12 =>Console ，可以看到无法建立链接。如果是在主页上，时间越久出现的个数越多。结果是网页版不会收到通知。
等有空我试着搭一个实例然后反馈给您。

**Comment by doubanius** [comment]
终于看到问题了！设法解决。

**Comment by doubanius** [comment]
又试了一下里面的两个办法，还是没搞定……

**Comment by mason1900** [comment]
正常来讲https://donotban.com/api/v1/streaming/?stream=user 如果用浏览器直接访问应该返回一个JSON.
比如你可以试一下https://bgme.me/api/v1/streaming/?stream=user.
应该就是配置的问题。等有空我试一下看看能不能在自己的服务器上复现这个bug

**Comment by doubanius** [comment]
发现问题了！mastodon服务器安装失误，streaming service一直没有开启！居然存活到了现在……
